config/routes.rb
SenchaGrid::Application.routes.draw do
  get "sencha_grid/grid"
  
  resources :users
  match '/users/create',  to: 'users#create'
  match '/users/update',  to: 'users#update'
  match '/users/destroy', to: 'users#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first, :last
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sencha_grid_controller.rb
class SenchaGridController < ApplicationController
  def grid
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users = User.all(:select => "id, email, first, last")
    respond_to do |format|
      format.json { render json: @users }
    end
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @users }
    #end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id], params[:id])

    respond_to do |format|
      #format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      #format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:data][:id])
    respond_to do |format|
      #format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:data])

    respond_to do |format|
      if @user.save
        format.json { render json: @user }
      else
        redirect_to @user
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:data][:id])

    if @user.update_attributes(params[:data])
      redirect_to @user
      #format.json { render json: @users }
      #format.html { redirect_to @user, notice: 'User was successfully updated.' }
      #format.json { head :no_content }
    else
      #format.html { render action: "edit" }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:data][:id])
    @user.destroy
    redirect_to @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sencha_grid_helper.rb
module SenchaGridHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SenchaGrid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
{"success":true,"message":"Updated <%=@users.length %> records","data":<%=@users.to_json %>}

app/views/users/index.html.erb
{"success":true,"message":"Loaded data","data":<%=@users.to_json %>}


app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First:</b>
  <%= @user.first %>
</p>

<p>
  <b>Last:</b>
  <%= @user.last %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>